/*
 * Translation unit for the VendorTunnel cluster's generated Encode/Decode.
 *
 * Why this file exists
 * --------------------
 * The Matter SDK's chip_data_model.cmake compiles cluster-objects.cpp from a
 * HARDCODED path:
 *
 *     ${CHIP_APP_BASE_DIR}/../../zzz_generated/app-common/.../cluster-objects.cpp
 *
 * unlike the neighbouring Accessors.cpp, which correctly honours
 * CHIP_APP_ZAP_DIR. So even with full ZAP generation and CHIP_APP_ZAP_DIR
 * redirected, the *implementations* still come from the SDK's copy, which knows
 * only standard clusters. The result is a link failure:
 *
 *     undefined reference to ... VendorTunnel::Commands::TunnelResponse::Type::Encode
 *     undefined reference to ... VendorTunnel::Commands::TunnelRequest::DecodableType::Decode
 *
 * Compiling our full generated cluster-objects.cpp instead is not an option: it
 * is a superset covering every standard cluster too, so it would collide with
 * the SDK's copy on hundreds of symbols.
 *
 * Generated per-cluster code lives in .ipp fragments, so this unit includes
 * only the four belonging to VendorTunnel. Nothing here is hand-written logic —
 * it is generated code, compiled in isolation.
 *
 * If the cluster gains attributes, events, or structs, these includes stay
 * correct; the .ipp files are regenerated by `west zap-generate -f`.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <app-common/zap-generated/cluster-objects.h>

#include <clusters/VendorTunnel/Attributes.ipp>
#include <clusters/VendorTunnel/Commands.ipp>
#include <clusters/VendorTunnel/Events.ipp>
#include <clusters/VendorTunnel/Structs.ipp>
